### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zzyybtxl** [hy-struggle/PRGC#11]
When I use multi_gpu to run train script,It shows 'zip argument #1 must support iteration',and I have already transferred the type of function evaluate's return to tensor.Can you tell me how to fix the issue?

**Comment by suexin27** [comment]
HI,When I use multi_gpu to run train script,It shows 'ValueError: only one element tensors can be converted to Python scalars',
Traceback (most recent call last):
  File "/PRGC-main/train.py", line 229, in <module>
    train_and_evaluate(model, params, ex_params, args.restore_file)
  File "/PRGC-main/train.py", line 150, in train_and_evaluate
    train(model, train_loader, optimizer, params, ex_params)
  File "/PRGC-main/train.py", line 84, in train
    loss_avg_seq.update(loss_seq.item())
Had you meet the issue,and can you tell me how to fix that?thanks!
