### ISSUE TITLE
After training one epoch, got an error

### ISSUE THREAD

**Issue by KeranLi** [hy-struggle/PRGC#23]
Epoch 1/100
100%|####################################################################################################| 89/89 [00:27<00:00,  3.25it/s, loss=0.288, loss_mat=0.000, loss_rel=0.000, loss_seq=0.288]
  0%|                                                                                                                                                                       | 0/2 [00:00<?, ?Batch/s] 
Traceback (most recent call last):
  File "train.py", line 224, in <module>
    train_and_evaluate(model, params, ex_params, args.restore_file)
  File "train.py", line 153, in train_and_evaluate
    val_metrics = evaluate(model, val_loader, params, ex_params, mark='Val')
  File "F:\code\PRGC\evaluate.py", line 92, in evaluate
    ex_params=ex_params)
ValueError: not enough values to unpack (expected 4, got 3)
_____________________________________________________________________________________
I'm so confused about this error. because I confirmed the output of the **evaluate** function is 3. The expected 4 is non-sense.

**Comment by 32209056** [comment]
同门那请问解决了吗

**Comment by 32209056** [comment]
同问，请问结局了吗

**Comment by 32209056** [comment]
同问，请问解决了吗

**Comment by 258508** [comment]
我也遇到了，请问解决了吗？

**Comment by KeranLi** [comment]
这个是缺少参数导致的，要添加上所有的配置参数

**Comment by 258508** [comment]
可以说一下加哪些参数吗？感谢！

**Comment by Wangrulin-1128** [comment]
我之前也遇到这个问题了 一开始在一个服务器上跑的好好 的 换了个服务器就报这个错 我的代码没有改动 后来换了个环境好了 我举得应该是环境的问题吧
